version: '3'
services: 
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/todo_frontend
    ports:
      - "8080:8080"
    command: [yarn, run, start]